field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  388eeda2-1a16-40f7-9efc-dddd8667d1ee:
    tabs:
      -
        elements:
          -
            fieldUid: 887377b8-bf93-4e5b-9f04-52b0cc0d6599
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  887377b8-bf93-4e5b-9f04-52b0cc0d6599:
    contentColumnType: text
    fieldGroup: null
    handle: article
    instructions: 'Enter one more paragraphs to create your textual content.'
    name: 'Body Content'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Content.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: article
name: 'Article Body'
sortOrder: 2
