field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  ad7febac-8d77-4398-8fbd-5b175d19641a:
    tabs:
      -
        elements:
          -
            fieldUid: 39a1747f-508a-4ea2-ba7e-8bc5c057563c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a9a1faa5-9ee8-4c3b-a8e0-9e94e95077c7
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bc3ff665-9a6b-4017-8ae7-e1d32a84363d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3ef590a8-8cd0-410c-98cf-4512c8a79131
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  39a1747f-508a-4ea2-ba7e-8bc5c057563c:
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: 'Enter your quote.'
    name: Quote
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3ef590a8-8cd0-410c-98cf-4512c8a79131:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: 'The position field only has an influence when the type Pull Quote has been selected.'
    name: Position
    searchable: false
    settings:
      default: left
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - ''
          -
            - right
            - '1'
          -
            - full
            - ''
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  a9a1faa5-9ee8-4c3b-a8e0-9e94e95077c7:
    contentColumnType: string
    fieldGroup: null
    handle: quoteSource
    instructions: 'Select an entry or enter an external url to point to the source of the quote.'
    name: 'Quote Source'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - enabled
                  - true
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - site
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - email
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - tel
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - url
            -
              __assoc__:
                -
                  - enabled
                  - true
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  bc3ff665-9a6b-4017-8ae7-e1d32a84363d:
    contentColumnType: string
    fieldGroup: null
    handle: quoteType
    instructions: 'Choose the type of quote.'
    name: Type
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Block Quote'
            -
              - value
              - blockQuote
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Pull Quote'
            -
              - value
              - pullQuote
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockQuote
name: Quotation
sortOrder: 5
