field: 7950ad45-9f8c-452f-aaaa-0e7e0aca0acf
fieldLayouts:
  f4a4a599-febe-4af9-bcb1-9ad00e914960:
    tabs:
      -
        elements:
          -
            fieldUid: 05b039b0-2a99-4543-b460-ff6cda276738
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  05b039b0-2a99-4543-b460-ff6cda276738:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heroContent
name: 'Content Header'
sortOrder: 1
