field: dbc7a062-ef19-48ca-bd6f-acda62a18b78 # Hero Builder
fieldLayouts:
  89badc98-776e-4c7c-bd92-c68959f103b0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d9bfce22-613d-44cc-bdac-b06404b4a8ea # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c2268c87-3e98-4362-9ad0-f049a4768f49
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b48b7930-d874-4662-85cb-5ec7a93ff95e # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30068398-456d-4800-a690-b8d3a911c45e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80a6157c-e287-49ae-a937-228b86f1ffa2 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee5a8ebd-45fa-4672-9877-069987d93c84
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25e21097-6c82-4437-9970-cfefaf1a3b79
        userCondition: null
fields:
  80a6157c-e287-49ae-a937-228b86f1ffa2: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: null
    name: Buttons
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1969395826
      columns:
        __assoc__:
          -
            - 6776ad6d-4fab-4c6f-a948-20e376cc6820 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_72_buttons}}'
      fieldLayout: table
      maxRows: 2
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: none
    type: verbb\supertable\fields\SuperTableField
  b48b7930-d874-4662-85cb-5ec7a93ff95e: # Description
    columnSuffix: dkwaifxb
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d9bfce22-613d-44cc-bdac-b06404b4a8ea: # Heading
    columnSuffix: mdgjldhh
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: heroSecondary
name: 'Hero Secondary'
sortOrder: 2
