field: dbc7a062-ef19-48ca-bd6f-acda62a18b78 # Hero Builder
fieldLayouts:
  49b2df8f-cf45-4beb-afd2-207579b23d01:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: df8a0480-96ec-4e76-bc8f-16b5e4f2fa3b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74a1265f-0f33-4689-8662-0f0c232da679
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 670882de-3f12-4bfd-b44e-7f5132526ff9 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 353e0594-7f1a-4074-88e9-05d9a39e461e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b54a377c-67b1-4122-97af-d6c7cd75fa5b
        userCondition: null
fields:
  670882de-3f12-4bfd-b44e-7f5132526ff9: # Description
    columnSuffix: idtsciuz
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: Description
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Simple.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  df8a0480-96ec-4e76-bc8f-16b5e4f2fa3b: # Heading
    columnSuffix: ukdeceos
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: null
    name: Heading
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: heroPrimary
name: 'Hero Primary'
sortOrder: 1
