field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  9d055ea2-c356-4758-8867-cae47dc11402:
    tabs:
      -
        elements:
          -
            fieldUid: c113c4fa-c4b4-439f-b4a6-8b3d66ae070c
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  c113c4fa-c4b4-439f-b4a6-8b3d66ae070c:
    contentColumnType: string
    fieldGroup: null
    handle: cards
    instructions: 'Select entries to be displayed on the page'
    name: Cards
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '2'
      localizeRelations: false
      selectionLabel: 'Add a card to highlight'
      showSiteMenu: true
      source: null
      sources:
        - 'section:9de367ab-77b8-47bb-bbc3-63e79a202c3e'
        - 'section:ef841ba4-7bcd-4ef5-9c12-96377bf7fba2'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: highlightCards
name: 'Highlight Cards'
sortOrder: 6
