field: e691301b-7484-40be-a3d4-c3bc590de959 # Content Builder
fieldLayouts:
  5158fab7-a860-4511-90c9-3e8f068fede3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6325f925-feea-4e28-b6ec-7630d3e70cc8 # Embed
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a364b70-e9be-4c39-a519-97c6c9b86de0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0a95661-f4fd-4a63-b2c2-edcf21f1cd58
        userCondition: null
fields:
  6325f925-feea-4e28-b6ec-7630d3e70cc8: # Embed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: embed
    instructions: 'This can be a Youtube video, Vimeo video, Instagram post, ...'
    name: Embed
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: false
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:916fd2eb-056d-486e-8483-bfff9c0a5520' # Teasers
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:1e7b8ff1-3532-4375-bd33-c7a4043dc5a6' # Media
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: 'Add an Embed URL'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: media
name: Media
sortOrder: 6
