field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  4e57d704-405a-4ead-bd39-fc3caacb7ca1:
    tabs:
      -
        elements:
          -
            fieldUid: 93863723-9e5b-4ca3-9264-940e320f4a63
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 844e44ed-99f1-4807-a8f7-6b8d2f32c612
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3907b6fa-b7ad-458d-829e-921e6b18bb2d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3907b6fa-b7ad-458d-829e-921e6b18bb2d:
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: 'Optionally add buttons to the section that can refer to another page or entry.'
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 03013785-a710-4dce-a0bd-263e0acfb5dd
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 847926b4-c795-4f3b-a415-c8e59ca58929
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_13_buttons}}'
      fieldLayout: row
      maxRows: '2'
      minRows: '1'
      placeholderKey: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  844e44ed-99f1-4807-a8f7-6b8d2f32c612:
    contentColumnType: string(480)
    fieldGroup: null
    handle: description
    instructions: 'Enter a short description what the section is about. Maximum 120 characters.'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: 120
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  93863723-9e5b-4ca3-9264-940e320f4a63:
    contentColumnType: text
    fieldGroup: null
    handle: header
    instructions: 'Enter a section heading from an article or a page, a page can contain multiple sections, this is preferably 1 -3 words.'
    name: Header
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sectionHeader
name: 'Section Header'
sortOrder: 3
