field: 73929e5d-0eaa-424c-8cd1-ce83b47fd733 # Page Builder
fieldLayouts:
  3817f653-c60a-4600-a22c-759add88ef6f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 345c4093-df0a-45dd-9d5f-47fb3fac8c7d # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a44e9a2-c512-4f20-91c0-594456328015
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18b34e3a-f594-41b2-81ca-6368fb8843c7
        userCondition: null
fields:
  345c4093-df0a-45dd-9d5f-47fb3fac8c7d: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'The full heading of the section header'
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sectionHeader
name: 'Section Header'
sortOrder: 3
