field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  0cc84e2c-0118-45d6-b9b5-51913f6125ec:
    tabs:
      -
        elements:
          -
            fieldUid: fa21f657-36bc-4559-a17c-a0eef628701d
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f50fdeed-76fd-4ccb-8869-e5f8cfd56d31
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0350223c-dfa5-434d-8289-bf43b6b89ac0
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d192726b-59f1-4fb3-b59f-364f7e0a1fa4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0350223c-dfa5-434d-8289-bf43b6b89ac0:
    contentColumnType: string
    fieldGroup: null
    handle: position
    instructions: ''
    name: Position
    searchable: false
    settings:
      default: center
      options:
        __assoc__:
          -
            - left
            - '1'
          -
            - center
            - '1'
          -
            - right
            - '1'
          -
            - full
            - '1'
          -
            - drop-left
            - ''
          -
            - drop-right
            - ''
    translationKeyFormat: null
    translationMethod: none
    type: rias\positionfieldtype\fields\Position
  d192726b-59f1-4fb3-b59f-364f7e0a1fa4:
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: 'Select the Aspect Ratio where you want the image to be displayed in, use live preview to see how it looks.'
    name: Ratio
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - none
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '1:1'
            -
              - value
              - is1by1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2:1'
            -
              - value
              - is2by1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - is4by3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3:4'
            -
              - value
              - is3by4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '7:5'
            -
              - value
              - is7by5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '8:5'
            -
              - value
              - is8by5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - is16by9
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '21:9'
            -
              - value
              - is21by9
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f50fdeed-76fd-4ccb-8869-e5f8cfd56d31:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Enter an optional caption for the image, if an image already contains a caption, this field will override the original one.'
    name: Caption
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: 'Enter an optional caption'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fa21f657-36bc-4559-a17c-a0eef628701d:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'Select or upload an image to use in the page.'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5c642d7e-b16b-4836-9575-668d75d242e5'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:dbb9d34a-ed00-430b-a6cd-e61927f7b2d5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: true
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: singleImage
name: Image
sortOrder: 4
