field: 55805748-502a-48b2-9107-cac1d3e9b18e
fieldLayouts:
  a13a95fe-0414-48ad-bcf1-e4b97e667ffe:
    tabs:
      -
        elements:
          -
            fieldUid: 6d8e5650-bf25-44a5-bce5-8f54dd2a2f73
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6d8e5650-bf25-44a5-bce5-8f54dd2a2f73:
    contentColumnType: text
    fieldGroup: null
    handle: standfirst
    instructions: 'Please enter an introductory paragraph, use this to start a page or an article where it is necessary to have an introductory text that stands out from the other copy'
    name: 'Introductory Paragraph'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: standfirst
name: Standfirst
sortOrder: 1
