columnSuffix: null
contentColumnType: string(1120)
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99 # General
handle: description
instructions: 'Used in the card, Google search results and when this page is shared on social media sites'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: 280
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
