contentColumnType: string
fieldGroup: 07a123c0-4e8e-4c19-a79e-61829f5d88c0
handle: pageBuilder
instructions: 'Use this builder to build up a page, every block has its own specific functionality'
name: 'Page Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
