field: 3907b6fa-b7ad-458d-829e-921e6b18bb2d
fieldLayouts:
  6caca5bd-78ce-4b7e-ac39-61b7252639b1:
    tabs:
      -
        elements:
          -
            fieldUid: 03013785-a710-4dce-a0bd-263e0acfb5dd
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 847926b4-c795-4f3b-a415-c8e59ca58929
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  03013785-a710-4dce-a0bd-263e0acfb5dd:
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: 'Select a page or entry you wish this button to link to'
    name: Target
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      defaultLinkName: entry
      defaultText: ''
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - category
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - entry
            -
              __assoc__:
                -
                  - enabled
                  - true
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - site
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowCustomQuery
                  - false
                -
                  - allowCrossSiteLink
                  - false
                -
                  - sources
                  - '*'
          -
            - custom
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - email
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - tel
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
          -
            - url
            -
              __assoc__:
                -
                  - enabled
                  - false
                -
                  - allowAliases
                  - false
                -
                  - disableValidation
                  - false
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  847926b4-c795-4f3b-a415-c8e59ca58929:
    contentColumnType: string
    fieldGroup: null
    handle: style
    instructions: ''
    name: Style
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
